$(document).ready(function(){
    $('.sidenav').sidenav();
    $('.materialboxed').materialbox();
    $('.scrollspy').scrollSpy();
    $('.btn').click(function(e){
        e.preventDefault();
    });
    $('.dropdown-trigger').dropdown();
});