import { SettingManager } from '../../common/code/settings';
import {
  PLUGINS_SETTING,
  PLUGINS_SETTING_KEY,
  PLUGINS_SETTING_DEFAULT,
  START_FULLSCREEN_SETTING,
  START_FULLSCREEN_SETTING_KEY,
  START_FULLSCREEN_SETTING_DEFAULT,
  START_MAXIMIZED_SETTING,
  START_MAXIMIZED_SETTING_KEY,
  START_MAXIMIZED_SETTING_DEFAULT,
  SHOW_MENU_BAR_WHEN_FULLSCREEN_SETTING,
  SHOW_MENU_BAR_WHEN_FULLSCREEN_SETTING_KEY,
  SHOW_MENU_BAR_WHEN_FULLSCREEN_SETTING_DEFAULT
} from '../../common/constants/settings';

export const pluginsSetting = new SettingManager<PLUGINS_SETTING>(PLUGINS_SETTING_KEY, PLUGINS_SETTING_DEFAULT);
export const startFullscreenSetting = new SettingManager<START_FULLSCREEN_SETTING>(START_FULLSCREEN_SETTING_KEY, START_FULLSCREEN_SETTING_DEFAULT);
export const startMaximizedSetting = new SettingManager<START_MAXIMIZED_SETTING>(START_MAXIMIZED_SETTING_KEY, START_MAXIMIZED_SETTING_DEFAULT);
export const showMenuBarWhenFullscreenSetting = new SettingManager<SHOW_MENU_BAR_WHEN_FULLSCREEN_SETTING>(SHOW_MENU_BAR_WHEN_FULLSCREEN_SETTING_KEY, SHOW_MENU_BAR_WHEN_FULLSCREEN_SETTING_DEFAULT);
